### ISSUE TITLE
Desktop Windows - No transactions found

### ISSUE THREAD

**Issue by Brad241** [Nexusoft/NexusInterface#205]
Recently upgraded Desktop wallet to 3.1.0 on Windows. On Lite mode the Block count has synced up, I logged into account but it is showing no transactions or NXS Balance. (Given I've been staking for over 2 years, this isn't correct.

**Comment by NamecoinGithub** [comment]
Just so you IDK about this problem I have only had minor bugs but I have worked around some things, but you can't stake using LITE-MODE if you still intended to do so!

**Comment by NamecoinGithub** [comment]
Is this still an ISSUE Brad?

**Comment by Brad241** [comment]
Yes - this remains an issue

**Comment by Brad241** [comment]
I am able to login, however it shows zero transactions and I also get an error message that the trust account doesn't exist. When I check my account on the Blockexplorer, everything is there...so not sure what is going on.

**Comment by NamecoinGithub** [comment]
Did you Uninstall Nexus before installing the new Version?  IDK about Windows but I know it's very buggy after updates!

I am surprised this is still an issue?  

Maybe you need to try a different device to login to Nexus?

But try uninstalling Nexus and if you haven't already delete the Nexus Blockchain folder and Resync 

Otherwise you probably need to Reinstall Windows to Recover from Malware!

IDK where to find the blockchain in Windows but in Linux it's .nexus hidden folder

**Comment by Brad241** [comment]
I have tried to login on three different devices and the same issue exists. I have uninstalled and deleted the Nexus Folder and resynced - same issue.
I can login via mobile wallet, but not desktop wallet.

**Comment by NamecoinGithub** [comment]
Ok, so this is only a Desktop LITE-MODE issue, I have personally not tested this feature, as it doesn't allow Staking, and why it wouldn't find your "Trust Account" might be related to being in LITE-MODE

Have you tried Downloading the Entire Blockchain NOT in LITE-MODE?   On Desktop?  And checking if Transactions show up?

Otherwise it's probably a database sync sinkhole that probably only requires a few lines of code for LITE-NODE to Sync with Full Node, and I cannot fix code like that personally!  But I might sign up as Nexus Dev in the Future using Github Co-Pilot after I learn to use it!

**Comment by Brad241** [comment]
Works fine in tritium mode. So looks like a lite mode issue

**Comment by KenCorma** [comment]
Have you experienced this issue with 3.1.1?
