### ISSUE TITLE
Feature Request - BTC value on click

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [Nexusoft/NexusInterface#73]
This is not a bug, simply a request for a feature that should be easily implemented.

Currently, when clicking nxs balance, it converts to chosen currency to show a total value. A great addon would be a 3rd click to show BTC value aswell. 

This should be accomplished fairly easily as the wallet already has and stores the nxs/btc value from the market page. I will make an attempt at it, but I dont want to wreck anything and am unsure I could properly code the third click.

**Comment by KenCorma** [comment]
I can take a look at this. Maybe what we do also is see if we can have btc on the drop down of currencies.

That being said it is also worth considering that eventually we don't want to be linked with BTC we are Nexus, we are different. We are only linked now because of the exchanges but hope one day we won't be bound by BTC.

**Comment by l8nit3tr0ubl3** [comment]
Working on this now, your option of adding btc to the currency list. Will submit PR when finished.

**Comment by Qrysto** [comment]
Great, I've been having the same idea for a long time - adding BTC and even NXS as the "base currency" (renamed from "fiat currency"). Looking forward to your PR!
