### ISSUE TITLE
Console tab re-design

### ISSUE THREAD

**Issue by pioruns** [Nexusoft/NexusInterface#83]
This is an enhancement request
using latest 1.2.0 deb on Debian Linux

Currently, the console tab works as follows:

You enter console command at the top of the window
Result of the command is being appended each time to the existing output window
If you scrolled up to read something, when a new command is entered, the window will not scroll down automatically for you

What I suggest to change:
Put "Enter console commands here" input window to the bottom of the page, so it works like every terminal
When a new command is entered, automatically scroll down to show the most recent result.

**Comment by Qrysto** [comment]
I agree with putting the input to the bottom of the page. 

About always scrolling down to the most recent result, the current behavior is that it will only scroll down if you're already at the bottom of the scroll, so that if you're reading some previous log you'll not lose track of it. But since there's only new log appended when you explicitly enter some command, and it's likely that you would always want to see the result, so your suggestion also makes sense.

**Comment by Qrysto** [comment]
After trying, I realized that if we bring the command input to the bottom, the command suggestions will breach out of the Panel and cause some styling issues. Fixing it requires significant efforts and this improvement is not really a high priority so I decided to keep the command input at the top for now and only update the scroll to bottom behavior.

**Comment by pioruns** [comment]
Awesome, thanks.
