### ISSUE TITLE
Inconsistency: Wallet allows you to see fiat balance on main and Send tab, but not on Transactions page

### ISSUE THREAD

**Issue by pioruns** [Nexusoft/NexusInterface#87]
This is an enhancement request.

Currently, I can switch from fiat to Nexus and back easily by clicking Icon on the main tab. I can see my Nexus balance and my fiat balance.
on Send tab, I can enter my desired Nexus or Fiat amount to send, and I will calculate for me automatically how much that will be Fiat/Crypto respectively.

However, Transactions tab is completely not supported, no fiat at all.

Please add fiat conversion to Transactions tab, as seen on main and send tabs.

**Comment by Qrysto** [comment]
This will be considered, but it's low priority at the moment. It's worth noting that deciding which fiat value of a transaction to display is complicated. You can show the fiat value of the same NXS amount to fiat at the current price, but what's arguably more important is the fiat value at the time the transaction was created, and in order to know it we need to fetch the historical price of NXS in that specific fiat currency

**Comment by KenCorma** [comment]
In the next update, if you go to a account's history you will be able to toggle on and off fiat display by clicking the underlined token under balances. For the actual history this is something that will have to come as a module later on, there is just no easy way to get history data and store it on the app, the overhead is not worth the dev time at this time.
